version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3301:3306"
    volumes:
      - ./mysql/initdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: photoapp
      MYSQL_ROOT_PASSWORD: root
    container_name: photoapp-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  redis:
    image: redis:3.2.9
    ports:
      - "6379:6379"
    container_name: photoapp-redis

  minio:
    image: minio/minio:latest
    ports:
      - 19000:9000
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: photoappaccess
      MINIO_SECRET_KEY: photoappsecret
    command: server /export