spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3301/photoapp
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379

doma:
  naming: SNAKE_LOWER_CASE
  dialect: mysql

#s3:
#  access-key: photoappaccess
#  secret-access-key: photoappsecret
#  bucket: photoapp20200503
#  url-template: http://127.0.0.1:19000/minio/articles/

s3:
  access-key: AKIAX5MZ63DX4Q5YT6Z2
  secret-access-key: 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
  bucket: photoapp20200503
  url-template: https://photoapp20200503.s3-ap-northeast-1.amazonaws.com/